version: "2"

services:
  fastapi:
    container_name: fastapi-container
    image: fastapi_image
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    volumes:
      - ./app:/code/app

  mysql:
    container_name: mysql-container
    image: mysql:5.7
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
