version: "3"

services:
  fastapi:
    image: fastapi
    container_name: fastapi
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    environment:
      TZ: Asia/Seoul
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    volumes:
      - ./app:/code/app

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql